"""Shared I/O: TUM trajectories and the repo's extrinsics YAML format."""
import numpy as np
import yaml
from scipy.spatial.transform import Rotation as R

from handeye import se3


def T_from_xyz_quat(xyz, q_xyzw):
    return se3(R.from_quat(q_xyzw).as_matrix(), np.asarray(xyz, float))


def load_tum(path):
    """Read a TUM trajectory: rows of 'timestamp tx ty tz qx qy qz qw'.

    Returns (times: (N,), poses: list of 4x4). Lines starting with '#' ignored.
    """
    times, poses = [], []
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        v = [float(x) for x in line.replace(",", " ").split()]
        if len(v) < 8:
            continue
        times.append(v[0])
        poses.append(T_from_xyz_quat(v[1:4], v[4:8]))
    if not poses:
        raise ValueError(f"No poses parsed from {path}")
    return np.asarray(times), poses


def load_extrinsics(path):
    """Parse extrinsics_initial.yaml -> (doc, {child: 4x4 T_parent_child})."""
    doc = yaml.safe_load(open(path))
    frames = {}
    for tf in doc["transforms"]:
        frames[tf["child"]] = T_from_xyz_quat(tf["xyz"], tf["q_xyzw"])
    return doc, frames


def write_calibrated_extrinsics(path, initial_doc, updates, provenance):
    """Write a calibrated extrinsics YAML matching the repo format.

    `updates`: {child_frame: 4x4 T_parent_child} to overwrite. All other
    transforms are copied from `initial_doc` unchanged and tagged as CAD-initial.
    """
    out = {
        "reference_frame": initial_doc.get("reference_frame", "base_link"),
        "units": {"translation": "meters", "rotation": "quaternion_xyzw"},
        "provenance": provenance,
        "transforms": [],
    }
    for tf in initial_doc["transforms"]:
        child = tf["child"]
        entry = {"source_frame": tf.get("source_frame"),
                 "parent": tf["parent"], "child": child}
        if child in updates:
            T = updates[child]
            entry["xyz"] = [float(x) for x in T[:3, 3]]
            entry["q_xyzw"] = [float(x) for x in R.from_matrix(T[:3, :3]).as_quat()]
            entry["calibrated"] = True
        else:
            entry["xyz"] = [float(x) for x in tf["xyz"]]
            entry["q_xyzw"] = [float(x) for x in tf["q_xyzw"]]
            entry["calibrated"] = False
            entry["note"] = "CAD initial estimate (not refined by this run)"
        out["transforms"].append(entry)

    with open(path, "w") as f:
        f.write("# Calibrated sensor extrinsics. Generated by extrinsic_calibration/lidar_lidar.\n")
        f.write("# Entries with calibrated: true were refined; others are CAD initial values.\n")
        f.write("# Do NOT overwrite extrinsics_initial.yaml or coordinate_systems.yaml.\n\n")
        yaml.safe_dump(out, f, sort_keys=False, default_flow_style=None)
